### PR TITLE
Ali 1

### PR DESCRIPTION
**Pull request by alikny**
this is  alis' perfect code, please merge it

### CODE REVIEW

**Comment by SF001User** [comment]
discussing this change heavily here

**Comment by SF001User** [comment]
can we fix line number 5

**Comment by SF001User** [comment]
and add an additional commit so we can merge

**Comment by alikny** [comment]
i already wrote a perfect code, and reviewed it again, and added new some functions

**Comment by alikny** [comment]
mates, please make some comments here, i ll merge it if you dont mind

**Comment by Doolatkan** [comment]
Waw I like this changes!

**Comment by Doolatkan** [comment]
**Hello from Czech**

**Comment by Doolatkan** [comment]
This project awesome!

**Comment by Doolatkan** [comment]
@alikny @eu3-user @Doolatkan @Akbar300 @alpiysl  :1st_place_medal:

**Comment by alpiysl** [comment]
we will do our best 👍

**Pull request merged**
